export type Room = {
  address: number;
  name: string;
};

export const Rooms: Room[] = [
  { address: 0xc2c2bb, name: "Room $91F8: Landing site" },
  { address: 0xc2d6e8, name: "Room $92B3: Gauntlet east" },
  { address: 0xc2dbc4, name: "Room $92FD: Crateria mainstreet" },
  { address: 0xc2e977, name: "Room $93AA: Landing site power bombs cave" },
  { address: 0xc2eb45, name: "Room $93FE: Wrecked Ship entrance" },
  { address: 0xc38e1f, name: "Room $9461: Pre orange zoomer hall" },
  { address: 0xc38ffe, name: "Room $948C: Pre moat room" },
  { address: 0xc39bfc, name: "Room $94CC: Crateria -> Maridia elevator" },
  { address: 0xc39db8, name: "Room $94FD: Wrecked Ship back door" },
  { address: 0xc3acdb, name: "Room $9552: East Crateria kago shaft" },
  { address: 0xc3b1ba, name: "Room $957D: East Crateria maze" },
  { address: 0xc3bb9b, name: "Room $95A8: Post Crateria maze yellow door" },
  { address: 0xc3bcd2, name: "Room $95D4: Crateria pipe tunnel" },
  { address: 0xc3bd6d, name: "Room $95FF: Moat" },
  { address: 0xc3c145, name: "Room $962A: Crateria -> Red Brinstar elevator" },
  { address: 0xc3c301, name: "Room $965B: Gauntlet west" },
  { address: 0xc3c80c, name: "Room $968F: Orange zoomer hall" },
  { address: 0xc3c998, name: "Room $96BA: Old Tourian escape shaft" },
  { address: 0xc3d9f7, name: "Room $975C: Old Mother Brain room" },
  { address: 0xc3df23, name: "Room $97B5: Crateria -> Blue Brinstar elevator" },
  { address: 0xc3e0d0, name: "Room $9804: Bomb Torizo" },
  { address: 0xc3e16e, name: "Room $9879: Pre Bomb Torizo hall" },
  { address: 0xc3e232, name: "Room $98E2: Pre Crateria map station hall" },
  { address: 0xc3e2fc, name: "Room $990D: Crateria slope" },
  { address: 0xc3e985, name: "Room $9938: Crateria -> Green Brinstar elevator" },
  { address: 0xc3eb35, name: "Room $9969: West Crateria kago hall" },
  { address: 0xc3ee60, name: "Room $99BD: Crateria space pirate shaft" },
  { address: 0xc3f4d3, name: "Room $99F9: Crateria spike floor room" },
  { address: 0xc4811e, name: "Room $9A44: Crateria bomb block hall" },
  { address: 0xc48232, name: "Room $9A90: Crateria chozo missile" },
  { address: 0xc48322, name: "Room $C98E: Wrecked Ship spike floor hall" },
  { address: 0xc49d2e, name: "Room $CA08: Wrecked Ship entrance treadmill" },
  { address: 0xc49eae, name: "Room $CA52, state $CA64: Wrecked Ship attic" },
  { address: 0xc4a2e7, name: "Room $CA52, state $CA7E: Wrecked Ship attic" },
  { address: 0xc4a720, name: "Room $CAAE: Wrecked Ship attic missile tank room" },
  { address: 0xc4a9ac, name: "Room $CAF6, state $CB08: Wrecked Ship mainstreet" },
  { address: 0xc4bdc0, name: "Room $CAF6, state $CB22: Wrecked Ship mainstreet" },
  { address: 0xc4d187, name: "Room $CB8B: Wrecked Ship flooded spikey hall" },
  { address: 0xc4d3ee, name: "Room $CBD5: Wrecked Ship east exit" },
  { address: 0xc4d883, name: "Room $CC27: Wrecked Ship chozo energy tank room" },
  { address: 0xc4e14e, name: "Room $CC6F: Pre Phantoon hall" },
  { address: 0xc4e58c, name: "Room $CD13: Phantoon" },
  { address: 0xc4e6a5, name: "Room $CD5C: Wrecked Ship first flooded room" },
  { address: 0xc4e94e, name: "Room $CDA8: Wrecked Ship obvious super missile room" },
  { address: 0xc4ea8f, name: "Room $CDF1, state $CE03: Wrecked Ship hidden super missile hall" },
  { address: 0xc4ed98, name: "Room $CDF1, state $CE1D: Wrecked Ship hidden super missile hall" },
  { address: 0xc4f0a1, name: "Room $CE40: Gravity suit room" },
  { address: 0xc4f1ce, name: "Room $9AD9: Green Brinstar mainstreet" },
  { address: 0xc58bd5, name: "Room $9B5B: Spore Spawn's super missile shaft" },
  { address: 0xc59642, name: "Room $9B9D: Pre Brinstar map room hall" },
  { address: 0xc59755, name: "Room $9BC8: Early supers room" },
  { address: 0xc59b00, name: "Room $9C07: Brinstar reserve tank room" },
  { address: 0xc59cac, name: "Room $9C5E: Fireflea room" },
  { address: 0xc5a15f, name: "Room $9CB3: Dachora room" },
  { address: 0xc5b54d, name: "Room $9D19: Charge beam room" },
  { address: 0xc5cba7, name: "Room $9D9C: Pre Spore Spawn hall" },
  { address: 0xc5ce34, name: "Room $9DC7: Spore Spawn" },
  { address: 0xc5d18f, name: "Room $9E11: Brinstar false wall super-sidehopper power bomb room" },
  { address: 0xc5d559, name: "Room $9E52: Brinstar diagonal room" },
  { address: 0xc5ded5, name: "Room $9E9F: Morph ball room" },
  { address: 0xc5e63a, name: "Room $9F11: Old Kraid entrance" },
  { address: 0xc5e86f, name: "Room $9F64: Blue Brinstar ceiling e-tank hall" },
  { address: 0xc5ecae, name: "Room $9FBA: n00b bridge" },
  { address: 0xc5ef71, name: "Room $9FE5: Brinstar false floor beetom room" },
  { address: 0xc5f057, name: "Room $A011: Brinstar false floor spike hall" },
  { address: 0xc5f43e, name: "Room $A051: Brinstar post false floor super missiles" },
  { address: 0xc5f4c9, name: "Room $A0A4: Post Spore Spawn supers hall" },
  { address: 0xc5f778, name: "Room $A0D2: Waterway" },
  { address: 0xc5fd50, name: "Room $A107: Blue Brinstar missile room" },
  { address: 0xc5fe1b, name: "Room $A130: Brinstar sidehopper wave-gate room" },
  { address: 0xc681c2, name: "Room $A15B: Brinstar post side-hopper wave-gate energy tank" },
  { address: 0xc68318, name: "Room $A1AD: Blue Brinstar boulder room" },
  { address: 0xc68437, name: "Room $A1D8: Blue Brinstar double missile room" },
  { address: 0xc684ee, name: "Room $A253: Red Tower" },
  { address: 0xc691e3, name: "Room $A293: Pre x-ray spike hall" },
  { address: 0xc69bf9, name: "Room $A2CE: X-ray room" },
  { address: 0xc69d70, name: "Room $A2F7: Red Brinstar damage boost hall" },
  { address: 0xc69f4b, name: "Room $A322: Red Brinstar -> Crateria elevator" },
  { address: 0xc6b31f, name: "Room $A37C: Red Brinstar super-sidehopper power bomb floor room" },
  { address: 0xc6b58c, name: "Room $A3AE: Early power bombs room" },
  { address: 0xc6b739, name: "Room $A3DD: Red Brinstar skree-duo hall" },
  { address: 0xc6b91c, name: "Room $A408: Pre spazer room" },
  { address: 0xc6bcc7, name: "Room $A447: Spazer room" },
  { address: 0xc6bd83, name: "Room $A471: Kraid BTS madness" },
  { address: 0xc6c469, name: "Room $A4B1: Kraid beetom room" },
  { address: 0xc6c630, name: "Room $A4DA: Kraid keyhunter hall" },
  { address: 0xc6cdb9, name: "Room $A521: Fake Kraid's room" },
  { address: 0xc6d2cb, name: "Room $A56B: Pre Kraid room" },
  { address: 0xc6d620, name: "Room $A59F: Kraid" },
  { address: 0xc6d88d, name: "Room $A5ED: Pre Tourian hall" },
  { address: 0xc6dee0, name: "Room $A6A1: Kraid's lair entrance" },
  { address: 0xc6e355, name: "Room $A6E2: Varia suit room" },
  { address: 0xc6e4a4, name: "Room $A75D: Post ice beam mockball hall" },
  { address: 0xc6e5f5, name: "Room $A788: Norfair lava hidden missile room" },
  { address: 0xc6ecb9, name: "Room $A7B3: First hot room" },
  { address: 0xc6f2e1, name: "Room $A7DE: Norfair mainstreet" },
  { address: 0xc6f8c1, name: "Room $A815: Ice beam mockball hall" },
  { address: 0xc782ed, name: "Room $A865: Ice beam practice room" },
  { address: 0xc784a3, name: "Room $A890: Ice beam room" },
  { address: 0xc785d6, name: "Room $A8B9: Pre ice beam shaft" },
  { address: 0xc78a47, name: "Room $A8F8: Crumble block platform shaft" },
  { address: 0xc78cfa, name: "Room $A923: Norfair slope" },
  { address: 0xc79d71, name: "Room $A98D: Crocomire" },
  { address: 0xc7a036, name: "Room $A9E5: Hi-jump room" },
  { address: 0xc7a18d, name: "Room $AA0E: Norfair grapple ceiling room" },
  { address: 0xc7aa70, name: "Room $AA41: Pre hi-jump room" },
  { address: 0xc7aeb3, name: "Room $AA82: Post Crocomire room" },
  { address: 0xc7b28b, name: "Room $AADE: Post Crocomire power bombs room" },
  { address: 0xc7b3e7, name: "Room $AB07: Post Crocomire shaft" },
  { address: 0xc7b780, name: "Room $AB3B: Post Crocomire fluctuating acid missiles cave" },
  { address: 0xc7bb6b, name: "Room $AB64: Double lake grapple practice room" },
  { address: 0xc7becb, name: "Room $AB8F: Huge jump room" },
  { address: 0xc7cd91, name: "Room $ABD2: Grapple practice shaft" },
  { address: 0xc7cfcd, name: "Room $AC00: Single lake grapple practice room" },
  { address: 0xc7d13c, name: "Room $AC2B: Grapple room" },
  { address: 0xc7d4fe, name: "Room $AC5A: Bubble Norfair reserve tank room" },
  { address: 0xc7d66f, name: "Room $AC83: Bubble Norfair pre reserve tank room" },
  { address: 0xc7d895, name: "Room $ACB3: Bubble Norfair mainstreet" },
  { address: 0xc7e08c, name: "Room $ACF0: Speed booster lavaquake" },
  { address: 0xc7eaa8, name: "Room $AD1B: Speed booster room" },
  { address: 0xc7ec03, name: "Room $AD5E: Lower Norfair -> Bubble Norfair" },
  { address: 0xc7ff02, name: "Room $ADAD: Pre wave beam room" },
  { address: 0xc88532, name: "Room $ADDE: Wave beam room" },
  { address: 0xc8865c, name: "Room $AE07: Norfair sinking kamer hall" },
  { address: 0xc88953, name: "Room $AE32: Norfair funes and lavaquake room" },
  { address: 0xc8943a, name: "Room $AE74: Pre Lower Norfair entrance shaft" },
  { address: 0xc89d5d, name: "Room $AEB4: Norfair multiviola and lavamen hall" },
  { address: 0xc89fe3, name: "Room $AEDF: Pre useless cave shaft" },
  { address: 0xc8a2cf, name: "Room $AF14: Lower Norfair entrance" },
  { address: 0xc8aa89, name: "Room $AF3F: Norfair -> Lower Norfair elevator" },
  { address: 0xc8abed, name: "Room $AF72: Norfair wave gate room" },
  { address: 0xc8b15b, name: "Room $AFA3: Norfair long lavaquake hall" },
  { address: 0xc8b4f9, name: "Room $AFCE: Boring near-Crocomire hall" },
  { address: 0xc8b853, name: "Room $AFFB: Norfair spike floor hall" },
  { address: 0xc8b9cf, name: "Room $B051: useless cave" },
  { address: 0xc8bb21, name: "Room $B07A: Pre speed booster lavaquake room" },
  { address: 0xc8bde8, name: "Room $B106: Norfair speed blockade hall" },
  { address: 0xc8c165, name: "Room $B139: Norfair stone zoomer shaft" },
  { address: 0xc8c4d3, name: "Room $B1E5: Golden chozo statue lava lake" },
  { address: 0xc8d59c, name: "Room $B236: Lower Norfair mainstreet" },
  { address: 0xc8e09d, name: "Room $B283: Golden Torizo" },
  { address: 0xc8e900, name: "Room $B2DA: Screw attack practice" },
  { address: 0xc8ebfd, name: "Room $B32E: Ridley" },
  { address: 0xc8edce, name: "Room $B37A: Pre Ridley hall" },
  { address: 0xc8f01f, name: "Room $B3A5: Lower Norfair power bomb floor shaft" },
  { address: 0xc8f40b, name: "Room $B3E1: Unused room" },
  { address: 0xc8f58b, name: "Room $B40A: Lower Norfair multi-level one-way shaft" },
  { address: 0xc8fcc5, name: "Room $B457: Lower Norfair breakable pillars hall" },
  { address: 0xc98222, name: "Room $B482: Lower Norfair holtz room" },
  { address: 0xc984d3, name: "Room $B4AD: Lower Norfair wall jumping space pirates shaft" },
  { address: 0xc9899f, name: "Room $B4E5: Lower Norfair lavaquake room" },
  { address: 0xc994ba, name: "Room $B510: Lower Norfair mini metal maze room" },
  { address: 0xc99ce2, name: "Room $B55A: Lower Norfair crumble walls power bomb room" },
  { address: 0xc99e7b, name: "Room $B585: Lower Norfair kihunter shaft" },
  { address: 0xc9a88c, name: "Room $B5D5: Lower Norfair super desgeega hall" },
  { address: 0xc9b1c7, name: "Room $B62B: Elite pirate hall" },
  { address: 0xc9b4ab, name: "Room $B656: Impossible's x-ray room" },
  { address: 0xc9c30d, name: "Room $B698: Ridley's energy tank" },
  { address: 0xc9c428, name: "Room $B6C1: Screw attack shaft" },
  { address: 0xc9c706, name: "Room $B6EE: Norfair rolling boulder shaft" },
  { address: 0xc9db52, name: "Room $CEFB, state $CF0D: n00b tube" },
  { address: 0xc9e129, name: "Room $CEFB, state $CF27: n00b tube" },
  { address: 0xc9e6ae, name: "Room $CF54: n00b tube west" },
  { address: 0xc9e809, name: "Room $CF80: n00b tube east" },
  { address: 0xc9f225, name: "Room $CFC9: Maridia mainstreet" },
  { address: 0xca8eff, name: "Room $D017: Maridia space pirate room" },
  { address: 0xcaa113, name: "Room $D055: Maridia spinning turtle room" },
  { address: 0xcaaf99, name: "Room $D08A: Maridia green gate hall" },
  { address: 0xcab24f, name: "Room $D0B9: Mt. Doom" },
  { address: 0xcace42, name: "Room $D104: Maridia -> Red Brinstar room" },
  { address: 0xcad474, name: "Room $D13B: Sandy Maridia missile and super missile room" },
  { address: 0xcadbc8, name: "Room $D16D: Sandy Maridia memu room" },
  { address: 0xcae458, name: "Room $D1A3: Maridia pink room" },
  {
    address: 0xcaf59c,
    name: "Room $D1DD: Sandy Maridia unused passage to Sandy Maridia mainstreet",
  },
  { address: 0xcb83db, name: "Room $D21C: Maridia broken glass tube room" },
  { address: 0xcb883a, name: "Room $D252: Maridia broken glass tube room east" },
  { address: 0xcb89e0, name: "Room $D27E: Plasma beam puyo room" },
  { address: 0xcb8bd4, name: "Room $D2AA: Plasma beam room" },
  { address: 0xcb9792, name: "Room $D2D9: Sandy Maridia thin platform hall" },
  { address: 0xcba0d0, name: "Room $D30B: Maridia -> Crateria elevator" },
  { address: 0xcba878, name: "Room $D340: Sandy Maridia mainstreet" },
  { address: 0xcbc64f, name: "Room $D387: Pre plasma beam shaft" },
  { address: 0xcbcd9f, name: "Room $D408: Maridia elevatube" },
  { address: 0xcbdcf3, name: "Room $D433: Sandy Maridia drowning sand pit room" },
  { address: 0xcbde8f, name: "Room $D461: Sand falls west" },
  { address: 0xcbe472, name: "Room $D48E: Elevatube south" },
  { address: 0xcbe899, name: "Room $D4C2: Sand falls east" },
  { address: 0xcbec32, name: "Room $D4EF: Maridia reserve tank room" },
  { address: 0xcbf580, name: "Room $D51E: PB #66 room" },
  { address: 0xcbfec8, name: "Room $D54D: Pre Maridia reserve tank room sand fall room" },
  { address: 0xcc80b8, name: "Room $D57A: Pre PB #66 room sand fall room" },
  { address: 0xcc82a8, name: "Room $D5A7: Snail room" },
  { address: 0xcca13b, name: "Room $D5EC: Sandy Maridia sand pit room" },
  { address: 0xcca34a, name: "Room $D617: Pre Botwoon Hallway" },
  { address: 0xccac48, name: "Room $D646: Pre Shaktool shaft" },
  { address: 0xccb843, name: "Room $D69A: Pre Shaktool shaft section" },
  { address: 0xccbd31, name: "Room $D6D0: Springball room" },
  { address: 0xccc22f, name: "Room $D6FD: Sand falls sand pit" },
  { address: 0xccc9f1, name: "Room $D72A: Maridia grapple room" },
  { address: 0xcce5b1, name: "Room $D78F: Pre Draygon room" },
  { address: 0xccee0c, name: "Room $D7E4: Maridia speed blockade hall" },
  { address: 0xccfa8d, name: "Room $D86E: Sandy Maridia sand falls room" },
  { address: 0xccfb88, name: "Room $D898: Sand falls" },
  { address: 0xccfd75, name: "Room $D8C5, state $D8D7: Shaktool" },
  { address: 0xcd8404, name: "Room $D8C5, state $D8F1: Shaktool" },
  { address: 0xcd8a37, name: "Room $D913: Maridia grapple wall shaft" },
  { address: 0xcd950e, name: "Room $D95E: Botwoon" },
  { address: 0xcd991e, name: "Room $D9AA: Space jump room" },
  { address: 0xcd9b28, name: "Room $D9FE: Plasma beam shortcut cacatac room" },
  { address: 0xcda00d, name: "Room $DA2B: Plasma beam shortcut spike room" },
  { address: 0xcdb19d, name: "Room $DA60: Draygon" },
  { address: 0xcdb846, name: "Room $DF45: Ceres elevator shaft" },
  { address: 0xcdbbfe, name: "Room $DF8D: Ceres pre elevator hall" },
  { address: 0xcdbd78, name: "Room $DFD7: Ceres stairs" },
  { address: 0xcdbfc9, name: "Room $E021: Ceres baby metroid hall" },
  { address: 0xcdc330, name: "Room $E06B: Pre Ceres Ridley hall" },
  { address: 0xcdc43f, name: "Room $E0B5: Ceres Ridley" },
  { address: 0xcdc4fe, name: "Room $DAAE: Tourian -> Crateria elevator" },
  { address: 0xcdc8dc, name: "Room $DAE1: Metroid room 1" },
  { address: 0xcdcda0, name: "Room $DB31: Metroid room 2" },
  { address: 0xcdd02d, name: "Room $DB7D: Metroid room 3" },
  { address: 0xcdd3e5, name: "Room $DBCD: Metroid room 4" },
  { address: 0xcdd5eb, name: "Room $DC19: Tourian super-sidehopper room" },
  { address: 0xcdd7c4, name: "Room $DC65: Drained Torizo room" },
  { address: 0xcdd930, name: "Room $DCB1: Shitroid room" },
  { address: 0xcddbf8, name: "Room $DCFF: Post Shitroid room" },
  { address: 0xcddede, name: "Room $DD58: Mother Brain" },
  { address: 0xcde20f, name: "Room $DDC4: Tourian eye-door room" },
  { address: 0xcde518, name: "Room $DDF3: Pre Mother Brain shaft" },
  { address: 0xcde914, name: "Room $DE4D: Escape room 1" },
  { address: 0xcdeb5b, name: "Room $DE7A: Escape room 2" },
  { address: 0xcded7a, name: "Room $DEA7: Escape room 3" },
  { address: 0xcdf534, name: "Room $DEDE: Escape room 4" },
  { address: 0xce83c3, name: "Room $9C35/$B0B4/$CCCB: Map station - right side door" },
  { address: 0xce86bd, name: "Room $9994/$D3B6: Map station - left side door" },
  { address: 0xce89b6, name: "Room $A07B/$A618: Energy station - right side door" },
  { address: 0xce8cb3, name: "Room $9C89: Missile station - right side door" },
  { address: 0xce8fa6, name: "Room $B026: Energy station - both doors" },
  {
    address: 0xce92cb,
    name: "Room $93D5/$A184/$A201/$A22A/$B0DD/$B1BB/$D765/$DE23: Save station - right side door",
  },
  {
    address: 0xce95c2,
    name: "Room $A70B/$A734/$AAB5/$B192/$B741/$CE8A/$CED2/$D3DF/$DF1B: Save station - left side door",
  },
  { address: 0xce98dc, name: "Room $B305/$D9D4: Energy station - left side door" },
  { address: 0xce9be9, name: "Room $A66A: Tourian entrance" },
  { address: 0xce9ef6, name: "Room $B167/$D81A: Draygon save station - both doors" },
  { address: 0xcea201, name: "Room $A641: Refill station - left side door" },
  { address: 0xcea823, name: "Room $DD2E: Refill station - right side door" },
  { address: 0xceab31, name: "Room $D845: Missile station - left side door" },
  { address: 0xceae3e, name: "Room $E82C: Debug room" },
];
